name: app_kontrakan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  appwrite: 17.0.1
  mime: ^2.0.0
  path: ^1.8.3
  intl: ^0.20.2
  file_picker: ^10.2.0
  google_fonts: ^6.1.0
  flutter_web_auth_2: ^4.0.2
  device_info_plus: ^10.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


